service: inventas-app-lambda
useDotenv: true

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  logRetentionInDays: 1
  timeout: 30
  stage: api
  environment: ${file(./env.local.yml)}

package:
  individually: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-offline:
    httpPort: ${file(./env.local.yml):APP_PORT}
