import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateEnums1721865796533 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    try {
      await queryRunner.query(`
        -- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

create type categories_status_enum as enum ('0', '1', '2', '3');
create type clients_document_type_enum as enum ('0', '1', '2', '3');
create type clients_status_enum as enum ('0', '1', '2', '3');
create type enterprises_status_enum as enum ('0', '1', '2', '3');
create type payments_status_enum as enum ('0', '1', '2', '3');
create type products_status_enum as enum ('0', '1', '2', '3');
create type sales_status_enum as enum ('0', '1', '2', '3');
create type sales_type_enum as enum ('0', '1');
create type user_details_document_type_enum as enum ('0', '1', '2', '3');
create type users_roles_enum as enum ('0', '1', '2', '3');
create type users_status_enum as enum ('0', '1', '2', '3');

CREATE TABLE IF NOT EXISTS public.categories
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    status categories_status_enum NOT NULL DEFAULT '2'::categories_status_enum,
    enterprise_id uuid,
    CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY (id),
    CONSTRAINT "UQ_18b87f694187986b0fb7429fcb6" UNIQUE (name, enterprise_id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    document_number character varying COLLATE pg_catalog."default" NOT NULL,
    document_type clients_document_type_enum NOT NULL,
    status clients_status_enum NOT NULL DEFAULT '2'::clients_status_enum,
    names character varying COLLATE pg_catalog."default" NOT NULL,
    surnames character varying COLLATE pg_catalog."default" NOT NULL,
    phone character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default",
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    enterprise_id uuid,
    CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY (id),
    CONSTRAINT "UQ_31ba0abae11187f18ec2a6594cc" UNIQUE (document_number, document_type)
);

CREATE TABLE IF NOT EXISTS public.enterprises
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    address character varying COLLATE pg_catalog."default",
    status enterprises_status_enum NOT NULL DEFAULT '0'::enterprises_status_enum,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    owner_id uuid NOT NULL,
    CONSTRAINT "PK_a019e9afe6517b4f2a4588f2cce" PRIMARY KEY (id),
    CONSTRAINT "UQ_85ab61ee8ba51427c2ddce7c0ac" UNIQUE (email),
    CONSTRAINT "UQ_f4c58d077b4dbb4a025bf94aee3" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.inventories
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    location character varying COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    enterprise_id uuid,
    CONSTRAINT "PK_7b1946392ffdcb50cfc6ac78c0e" PRIMARY KEY (id),
    CONSTRAINT "UQ_ca4c6c3abea84f4ea813467cc7f" UNIQUE (location)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    total_amount numeric(10, 2) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    client_id uuid,
    enterprise_id uuid,
    status payments_status_enum NOT NULL DEFAULT '2'::payments_status_enum,
    CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_inventories
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    quantity integer NOT NULL,
    product_id uuid,
    inventory_id uuid,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_7ff88ac3f0221978eea3f9f999a" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    barcode character varying COLLATE pg_catalog."default",
    sale_price numeric NOT NULL,
    cost_price numeric NOT NULL,
    status products_status_enum NOT NULL DEFAULT '2'::products_status_enum,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    enterprise_id uuid,
    category_id uuid,
    subcategory_id uuid,
    "requiresInventory" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY (id),
    CONSTRAINT "UQ_4c9fb58de893725258746385e16" UNIQUE (name),
    CONSTRAINT "UQ_adfc522baf9d9b19cd7d9461b7e" UNIQUE (barcode),
    CONSTRAINT "UQ_bbdad5523aa4b40269602959fdc" UNIQUE (name, enterprise_id)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    total_amount numeric(10, 2) NOT NULL,
    status sales_status_enum NOT NULL DEFAULT '2'::sales_status_enum,
    type sales_type_enum NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    enterprise_id uuid,
    inventory_id uuid NOT NULL,
    client_id uuid,
    CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sales_details
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    product_id uuid,
    sale_id uuid,
    CONSTRAINT "PK_347905aa7874a8beb27680a8709" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subcategories
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    "categoryId" uuid,
    CONSTRAINT "PK_793ef34ad0a3f86f09d4837007c" PRIMARY KEY (id),
    CONSTRAINT "UQ_45aa12007713728e241d091775d" UNIQUE (name, "categoryId")
);

CREATE TABLE IF NOT EXISTS public.user_details
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    first_name character varying COLLATE pg_catalog."default" NOT NULL,
    last_name character varying COLLATE pg_catalog."default" NOT NULL,
    document_number character varying COLLATE pg_catalog."default" NOT NULL,
    document_type user_details_document_type_enum NOT NULL,
    phone character varying COLLATE pg_catalog."default" NOT NULL,
    gender boolean NOT NULL,
    birthdate date NOT NULL,
    CONSTRAINT "PK_fb08394d3f499b9e441cab9ca51" PRIMARY KEY (id),
    CONSTRAINT "UQ_4c273f0161a72587516fd21a517" UNIQUE (document_number, document_type)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    status users_status_enum NOT NULL DEFAULT '1'::users_status_enum,
    roles users_roles_enum[] NOT NULL,
    user_detail_id uuid,
    enterprise_id uuid,
    CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY (id),
    CONSTRAINT "REL_7fbd789ba2d9f9643ff3be7e7b" UNIQUE (user_detail_id),
    CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE (email)
);

ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT "FK_9c11e0bb5d9b03b64c9c114cb85" FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clients
    ADD CONSTRAINT "FK_3e897e8b4e0c73d8e13bca35394" FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enterprises
    ADD CONSTRAINT "FK_a6119f794fe01dbc13442a73159" FOREIGN KEY (owner_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventories
    ADD CONSTRAINT "FK_8d06f7ce99fd8e3fe38ed0e97fd" FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT "FK_bce3f30c3460065a6aeca163258" FOREIGN KEY (client_id)
        REFERENCES public.clients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT "FK_df53ea67b381868636625eaf425" FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_inventories
    ADD CONSTRAINT "FK_d340c0166d9bfb981aa0a94c413" FOREIGN KEY (inventory_id)
        REFERENCES public.inventories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_inventories
    ADD CONSTRAINT "FK_e934d1044fc107e226491eee0b6" FOREIGN KEY (product_id)
        REFERENCES public.products (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "FK_1b2bfc1c37bceb3088b2fae04cc" FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY (category_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "FK_c9de3a8edea9269ca774c919b9a" FOREIGN KEY (subcategory_id)
        REFERENCES public.subcategories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT "FK_914d05e8cb36114a16035605c7b" FOREIGN KEY (inventory_id)
        REFERENCES public.inventories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT "FK_c49d95226945ca3a93584f912ca" FOREIGN KEY (client_id)
        REFERENCES public.clients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT "FK_e309f2dc7c1b99278606b13f35e" FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_details
    ADD CONSTRAINT "FK_3b8a57faaababc72063ac2ef82b" FOREIGN KEY (product_id)
        REFERENCES public.products (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_details
    ADD CONSTRAINT "FK_5846c41781c1b40ee061430f6c6" FOREIGN KEY (sale_id)
        REFERENCES public.sales (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subcategories
    ADD CONSTRAINT "FK_d1fe096726c3c5b8a500950e448" FOREIGN KEY ("categoryId")
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT "FK_7fbd789ba2d9f9643ff3be7e7b0" FOREIGN KEY (user_detail_id)
        REFERENCES public.user_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_7fbd789ba2d9f9643ff3be7e7b"
    ON public.users(user_detail_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT "FK_fbe644d8ff0b13dae28f312b987" FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;
      `);
    } catch (error) {
      throw error;
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    try {
      await queryRunner.query(`
      
    drop table migrations cascade;
    
    alter table enterprises
        drop constraint "FK_a6119f794fe01dbc13442a73159" cascade;
    
    drop table payments cascade;
    
    drop table product_inventories cascade;
    
    drop table sales_details cascade;
    
    drop table products cascade;
    
    drop table sales cascade;
    
    drop table clients cascade;
    
    drop table inventories cascade;
    
    drop table subcategories cascade;
    
    drop table categories cascade;
    
    drop table users cascade;
    
    drop table enterprises cascade;
    
    drop table user_details cascade;


        DROP TYPE IF EXISTS categories_status_enum;
        DROP TYPE IF EXISTS clients_document_type_enum;
        DROP TYPE IF EXISTS clients_status_enum;
        DROP TYPE IF EXISTS enterprises_status_enum;
        DROP TYPE IF EXISTS payments_status_enum;
        DROP TYPE IF EXISTS products_status_enum;
        DROP TYPE IF EXISTS sales_status_enum;
        DROP TYPE IF EXISTS sales_type_enum;
        DROP TYPE IF EXISTS user_details_document_type_enum;
        DROP TYPE IF EXISTS users_roles_enum;
        DROP TYPE IF EXISTS users_status_enum;
      `);
    } catch (error) {
      throw error;
    }
  }
}
